
name: 'curso_data_engineering_art'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  +transient: false
  curso_data_engineering_art:
    # Applies to all files under models/staging/ and models/marts/
    staging:
      +materialized: view
      +database: "PAINTERPALETTE_DEV_SILVER_DB"
      painterpalette:
        +schema: painterpalette
    
    marts:
      +materialized: table
      +database: "PAINTERPALETTE_DEV_GOLD_DB"
      core:
        +schema: core

seeds:
  +schema: "SEEDS"
  +database: "PAINTERPALETTE_DEV_BRONZE_DB"
  +column_types:
    country: varchar(64)
    demonym: varchar(64)

    
  
snapshots:
  +transient: false
  +target_database: "PAINTERPALETTE_DEV_SILVER_DB"
  +target_schema: snapshots



vars:
  art_school_null: "'noartschool'"
  art_school_null_message: "'Unknown'"
  style_null: "'nostyle'"
  style_null_message: "'Unknown'"
  artist_null: "'noartist'"
  artist_null_message: "'Unknown'"
  place_null: "'noplace'"
  place_null_message: "'Unknown'"
  medium_null: "'nomedium'"
  medium_null_message: "'Unknown'"
  genre_null: "'nogenre'"
  genre_null_message: "'Unknown'"
  gender_null: "'nogender'"
  gender_null_message: "'Unknown'"
  contemporary_null: "'nocontemporary'"
  contemporary_null_message: "'Unknown'"
