
name: 'curso_data_engineering_art'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In dbt, the default materialization for a model is a view. This means, when you run 
# dbt run or dbt build, all of your models will be built as a view in your data platform. 
# The configuration below will override this setting for models in the example folder to 
# instead be materialized as tables. Any models you add to the root of the models folder will 
# continue to be built as views. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.

models:
  +transient: false
  curso_data_engineering_art:
    # Applies to all files under models/staging/ and models/marts/
    staging:
      +materialized: view
      +database: "PAINTERPALETTE_DEV_SILVER_DB"
      painterpalette:
        +schema: painterpalette
    
    marts:
      +materialized: table
      +database: "PAINTERPALETTE_DEV_GOLD_DB"
      core:
        +schema: core

seeds:
  +schema: "SEEDS"
  +database: "PAINTERPALETTE_DEV_BRONZE_DB"
  
snapshots:
  +transient: false
  +target_database: "PAINTERPALETTE_DEV_SILVER_DB"
  +target_schema: snapshots